name: minicam
description: "A Mini Cam application project with Live Photo support."
publish_to: 'none'
version: 1.7.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0
  permission_handler: ^11.3.0
  path_provider: ^2.1.3
  path: ^1.9.0
  image: ^4.3.0
  gal: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
